name: Teleport
main: Clarence2810\Teleport\teleport
version: 2
api: [3.0.0, 4.0.0]
author: Clarence2810, princepines
dependencies: 
   - Slapper
   - Wilderness

commands:
  hub:
    description: Teleport to Main Hub
    alias:
    - lobby
  potpvp:
    description: Teleport to PotPvP Arena
    alias:
    - pvp
  plots:
    description: Teleport to Plots
    alias: 
    - creative
  factions:
    description: Teleport to Factions
    alias:
    - fw
  facworld:
    description: Teleport Directly to Factions World
  shop:
    description: Teleport to Factions Shop
